### PR TITLE
reorganize and put all files under alarmdb folder

### PR DESCRIPTION
**Pull request by linsong**
with the help of updating include_path config in php, we can put all
alarmdb related files under one folder. in CPT Graphics, the place for
plugin will be 'cpt/plugins', CPT Graphics will detect this folder and
will render a plugin button on UI when it finds any plugin available.

### CODE REVIEW

**Comment by linsong** [comment]
Hi @automatikas, this is vincent, the developer of CPT Tools. Thanks for the alarmDB project! 

I just improved CPT Graphics to support plugin better, for now, it will try to find any plugin under the folder cpt/plugins, it will render a plugin button on UI if any plugin found. 

In the above pull request, I update alarmdb a bit so that user doesn't need to put files under cpt/app folder any more. Hope that will make things easier.

**Comment by automatikas** [comment]
Vincent that's amazing! Thanks for contribution.

Where can i get the modified graphics files for test?

`grweb/public/plugins/alarmdb` will be the path to copy all so deploy will copy files to web server?

**Comment by linsong** [comment]
@automatikas  yeah, you just need to put the alarmDB folder under CPT/grweb/public, CPT Tools will deploy it to /WEBROOT/sdcard/cpt/plugins folder, so that CPT Graphics can detect it. 

Here are the changed files: [plugin_update.zip](https://github.com/automatikas/AlarmDB-EasyIO/files/1526997/plugin_update.zip)

If your local copy of CPT Tools is too old, suggest you to download the last week's internal release from [here](https://www.dropbox.com/s/5s5lidlortfslm5/cpt-dev_20171201.zip?dl=0).

**Comment by automatikas** [comment]
@linsong 

Plugin directory iterator on graphics.php needs depth setting. If plugin has other folders with index it is rendered as separate plugin. `$paths->setMaxDepth(0);` will do the job.

small upgrade:
[graphic.zip](https://github.com/automatikas/AlarmDB-EasyIO/files/1550595/graphic.zip)



```
public function plugins() {
    $plugins = array();
    $pluginsPath = pluginsPath();
    if (file_exists($pluginsPath) && is_dir($pluginsPath))
    {
	  $paths = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($pluginsPath, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
	  $paths->setMaxDepth(0);
      foreach($paths as $path) {
        if (!$path->isDir())
          continue;
		
        $indexFile = NULL;
        if (file_exists(build_file_path($path->getPathName(), "index.php")))
          $indexFile = "index.php";
        else if (file_exists(build_file_path($path->getPathName(), "index.html"))) 
          $indexFile = "index.html";
        else if (file_exists(build_file_path($path->getPathName(), "index.htm")))
          $indexFile = "index.htm";
        else
          continue;

        $baseName = $path->getBaseName();
        $url = "plugins/" . $baseName . '/' . $indexFile;
        $plugins[] = array("name" => $baseName, 
            "url" => $this->makeUrl($url));
      }
    }

    return $plugins;
  }
```

**Comment by linsong** [comment]
@automatikas great! I have merged your changes into CPT Tools, thanks!

**Pull request merged**
